const express = require('express')
const passport = require('passport')
const router = express.Router()

const validatorControllers = require('../controllers/validatorControllers')
const userControllers = require('../controllers/userControllers')
router.route('/user/register')
.post(
    validatorControllers.validatorSignUp,
    userControllers.registerUser
)
router.route('/user/login')
.post(userControllers.logUser)
router.route('/user/logout')
.get(userControllers.logOut)
router.route('/user/validate')
.get(userControllers.logFromSession)
router.route('/user/admin/manage')
.put(
    passport.authenticate('jwt', {session: false}),
    userControllers.manageAdmin
)
router.route('/users/')
.get(userControllers.getUsers)
router.route('/user/manage')
.put(userControllers.manageUser)
router.route('/user/:id')
.delete(userControllers.removeUser)
router.route('/user/email/send')
.post(userControllers.sendResetPasswordMail)
router.route('/user/resetpassword/:id')
.put(userControllers.resetUserPassword)
const productControllers = require('../controllers/productControllers')
router.route('/products')
.post(productControllers.getProducts)
router.route('/product/add')
.post(productControllers.addProduct)
router.route('/product/:id')
.get(productControllers.getAProduct)
.put(productControllers.modifyProduct)
.delete(productControllers.deleteProduct)
const orderControllers = require('../controllers/orderControllers')
router.route('/orders')
.post(orderControllers.getOrders)
router.route('/order/new')
.post(orderControllers.newOrder)
router.route('/order/:id')
.get(orderControllers.getAnOrder)
.put(orderControllers.modifyOrder)
.delete(orderControllers.deleteOrder)
const cardControllers = require('../controllers/cardControllers')
router.route('/cards')
.get(cardControllers.getCards)
.post(cardControllers.addCard)
router.route('/card/:id')
.get(cardControllers.getCard)
.put(cardControllers.editCard)
.delete(cardControllers.deleteCard)
const paymentControllers = require('../controllers/paymentControllers')
router.route('/process-payment')
.post(paymentControllers.payWithMercadoPago)
module.exports = router