const express = require('express')
const passport = require('passport')
const router = express.Router()

const validatorControllers = require('../controllers/validatorControllers')
const userControllers = require('../controllers/userControllers')
router.route('/user/register')
.post(
    validatorControllers.validatorSignUp,
    userControllers.registerUser
)
router.route('/user/login')
.post(userControllers.logUser)
router.route('/user/logout')
.get(userControllers.logOut)
router.route('/user/validate')
.get(userControllers.logFromSession)
router.route('/user/admin/manage')
.put(userControllers.manageAdmin)
router.route('/users/')
.get(userControllers.getUsers)
router.route('/user/manage')
.put(userControllers.manageUser)
router.route('/user/:id')
.delete(userControllers.removeUser)
const productControllers = require('../controllers/productControllers')
router.route('/products')
.post(productControllers.getProducts)
router.route('/product/add')
.post(productControllers.addProduct)
router.route('/product/:id')
.get(productControllers.getAProduct)
.put(productControllers.modifyProduct)
.delete(productControllers.deleteProduct)
const orderControllers = require('../controllers/orderControllers')
router.route('/orders')
.post(orderControllers.getOrders)
router.route('/order/new')
.post(orderControllers.newOrder)
router.route('/order/:id')
.get(orderControllers.getAnOrder)
.put(orderControllers.modifyOrder)
.delete(orderControllers.deleteOrder)

module.exports = router